apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awesometarkov-com-dev-tls
  namespace: awesometarkov-com-dev
spec:
  secretName: awesometarkov-com-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - awesometarkov-com.9m.se
