apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-dev
  namespace: awesometarkov-com-dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`awesometarkov-com.9m.se`)
      services:
        - name: web
          port: 80
  tls:
    secretName: awesometarkov-com-dev-tls
