blank_issues_enabled: false
contact_links:
  - name: Tarkov.dev Community
    url: https://discord.gg/tarkov-dev
    about: Join the tarkov.dev Discord for community discussion
  - name: Official EFT Discord
    url: https://discord.com/invite/escapefromtarkovofficial
    about: Official Escape From Tarkov community Discord
